version: "3.4"
services:

  frontend:
    build:
      context: ./
      target: dev
    command: /bin/sh -c "npm install && npm run start"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8080

